version: '3.8'

services:
  luna2000:
    image: luna2000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
    container_name: luna2000
    expose:
      - 8080
    volumes:
      - /home/luna-data/files:/app/files
      - /home/luna-data/db:/app/DB
      - /home/luna-data/web-api-configs:/app/Configs
    networks:
      - luna2000_network
    environment:
      - telegram
      - ASPNETCORE_URLS=http://+:8080
      - VIRTUAL_HOST=t196driveboss.ru
      - LETSENCRYPT_HOST=t196driveboss.ru
      - LETSENCRYPT_EMAIL=dimka0512@yandex.ru

  job-server:
    image: job-server
    container_name: job-server
    depends_on:
      - luna2000
    ports:
      - "7890:7890"
    volumes:
      - /home/luna-data/job-server-configs:/app/Configs
    networks:
      - luna2000_network

  storage:
    image: silverwind/droppy
    container_name: luna-storage
    ports:
      - "8899:8989"
    volumes:
      - /home/luna-data:/files

networks:
    luna2000_network:
      driver: bridge
