name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t luna2000:latest .

    - name: Login to server via SSH with password and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Останавливаем текущий контейнер
          docker stop $(docker ps -q --filter ancestor=luna2000:latest) || true
          
          # Удаляем старый контейнер
          docker rm $(docker ps -a -q --filter ancestor=luna2000:latest) || true
          
          # Запускаем новый контейнер
          docker run -p 80:3000 -d luna2000:latest
