name: Deploy to Server

on:
  push:
    branches:
      - asp-net-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        cd backend-asp-net/luna2000
        docker build -t luna2000 .
        # Проверяем успешность сборки
        # docker images | grep luna2000 || exit 1

        cd ../Job\ server/
        docker build -t job-server .

        cd ../../

    - name: Save Docker image to file in /tmp
      run: |
        docker save luna2000 -o /tmp/web-api.tar
        docker save job-server -o /tmp/job-server.tar

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Copy Docker image to server via SCP
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no /tmp/web-api.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp
        sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no /tmp/job-server.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp
        sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no -r ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/luna2000-source/
    - name: Login to server via SSH with password and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/luna2000-source

          # Останавливаем текущий контейнер
          #docker stop $(docker ps -q --filter ancestor=luna2000:latest) || true
          
          # Удаляем старый контейнер
          #docker rm $(docker ps -a -q --filter ancestor=luna2000:latest) || true
          
          # Удаляем старый образ
          #docker rmi luna2000:latest || true
          
          # Загружаем новый образ
          docker load -i /tmp/web-api.tar
          docker load -i /tmp/job-server.tar

          docker compose up -d

          # Запускаем новый контейнер
          #docker run -p 80:3000 -d luna2000:latest

          # Удаляем архив с образом с сервера
          rm /tmp/web-api.tar
          rm /tmp/job-server.tar
          rmdir /home/luna2000-source

          docker system prune -f
