name: .NET Build

on:
  push:
    branches:
      - disable
  pull_request:
    branches:
      - disable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore "backend-asp-net/luna2000/luna2000.sln"

    - name: Build
      run: dotnet build "backend-asp-net/luna2000/luna2000.sln" --no-restore -c Release